parameters:
- name: stageName
  default: ''
- name: jobName
  default: ''
- name: artefactName
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''

jobs:
  - job:
    steps:
     - task: DownloadPipelineArtifact@2
       displayName: "Download Pipelien Artifact"
       inputs:
         artifactName: $(artefactName)
         targetPath: $(Build.ArtifactStagingDirectory)

      - task: AzureRmWebAppDeployment@4
        displayName: 'azure API service deployment'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: $(azureSubscription)
          appType: 'apiApp'
          WebAppName: $(webAppName)
          packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'