parameters:
- name: stageName
  default: ''
- name: jobName
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: artefactName
  default: ''

stages:
     - stage: ${{ parameters.stageName }}
       dependsOn:
         - Build
       condition: succeeded('Build')
       jobs:
           - template: deployjob.yml
             parameters:
               stageName: ${{ parameters.stageName }}
               jobName: 'Deploy'
               azureSubscription: ${{ parameters.azureSubscription }}
               webAppName: ${{ parameters.webAppName }}
               artefactName: ${{ parameters.artefactName }}